// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqEsnu3KE2hTn5Wtt2dJlDqqDLiEJxG20',
    appId: '1:631395287647:web:8761dfb20b975c8c4e11ea',
    messagingSenderId: '631395287647',
    projectId: 'treasurehomes',
    authDomain: 'treasurehomes.firebaseapp.com',
    storageBucket: 'treasurehomes.firebasestorage.app',
    measurementId: 'G-G5D9W0XM1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuPXmxaDnbYZm71-rcA_PLDdu9GYFLLuk',
    appId: '1:631395287647:android:8c2d684fcc9d8bd04e11ea',
    messagingSenderId: '631395287647',
    projectId: 'treasurehomes',
    storageBucket: 'treasurehomes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx09o8yV5yc_UrOqigYgkbUV-yBQ_jYvs',
    appId: '1:631395287647:ios:26ae869fce7aadf94e11ea',
    messagingSenderId: '631395287647',
    projectId: 'treasurehomes',
    storageBucket: 'treasurehomes.firebasestorage.app',
    iosBundleId: 'com.example.homeServicesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx09o8yV5yc_UrOqigYgkbUV-yBQ_jYvs',
    appId: '1:631395287647:ios:26ae869fce7aadf94e11ea',
    messagingSenderId: '631395287647',
    projectId: 'treasurehomes',
    storageBucket: 'treasurehomes.firebasestorage.app',
    iosBundleId: 'com.example.homeServicesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqEsnu3KE2hTn5Wtt2dJlDqqDLiEJxG20',
    appId: '1:631395287647:web:6fdc2b3f21dba48a4e11ea',
    messagingSenderId: '631395287647',
    projectId: 'treasurehomes',
    authDomain: 'treasurehomes.firebaseapp.com',
    storageBucket: 'treasurehomes.firebasestorage.app',
    measurementId: 'G-P62JZQBVXQ',
  );
}
