import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../subscriptions/data/repositories/firestore_subscription_repository.dart';
import '../../../subscriptions/domain/entities/subscription_plan_entity.dart';

class AddEditSubscriptionPage extends ConsumerStatefulWidget {
  final SubscriptionPlanEntity? plan;

  const AddEditSubscriptionPage({super.key, this.plan});

  @override
  ConsumerState<AddEditSubscriptionPage> createState() =>
      _AddEditSubscriptionPageState();
}

class _AddEditSubscriptionPageState
    extends ConsumerState<AddEditSubscriptionPage> {
  final _formKey = GlobalKey<FormState>();
  late TextEditingController _nameController;
  late TextEditingController _descriptionController;
  late TextEditingController _priceController;
  late TextEditingController _durationController;
  List<TextEditingController> _featureControllers = [];

  bool _isLoading = false;

  @override
  void initState() {
    super.initState();
    _nameController = TextEditingController(text: widget.plan?.name ?? '');
    _descriptionController = TextEditingController(
      text: widget.plan?.description ?? '',
    );
    _priceController = TextEditingController(
      text: widget.plan?.price.toString() ?? '',
    );
    _durationController = TextEditingController(
      text: widget.plan?.duration ?? 'Monthly',
    );

    if (widget.plan != null) {
      for (var feature in widget.plan!.features) {
        _featureControllers.add(TextEditingController(text: feature));
      }
    } else {
      _featureControllers.add(
        TextEditingController(),
      ); // Start with one empty feature
    }
  }

  @override
  void dispose() {
    _nameController.dispose();
    _descriptionController.dispose();
    _priceController.dispose();
    _durationController.dispose();
    for (var controller in _featureControllers) {
      controller.dispose();
    }
    super.dispose();
  }

  void _addFeature() {
    setState(() {
      _featureControllers.add(TextEditingController());
    });
  }

  void _removeFeature(int index) {
    if (_featureControllers.length > 1) {
      setState(() {
        final controller = _featureControllers.removeAt(index);
        controller.dispose();
      });
    }
  }

  Future<void> _savePlan() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isLoading = true);

    try {
      final name = _nameController.text.trim();
      final description = _descriptionController.text.trim();
      final price = double.tryParse(_priceController.text) ?? 0.0;
      final duration = _durationController.text.trim();
      final features = _featureControllers
          .map((c) => c.text.trim())
          .where((t) => t.isNotEmpty)
          .toList();

      final repo = ref.read(firestoreSubscriptionRepositoryProvider);

      if (widget.plan == null) {
        // Add new
        final newPlan = SubscriptionPlanEntity(
          id: '', // ID generated by Firestore usually, but entity needs one. Firestore add() returns ref.
          // In addPlan implementation we ignore ID for add().
          name: name,
          description: description,
          price: price,
          duration: duration,
          features: features,
        );
        await repo.addPlan(newPlan);
      } else {
        // Update existing
        final updatedPlan = SubscriptionPlanEntity(
          id: widget.plan!.id,
          name: name,
          description: description,
          price: price,
          duration: duration,
          features: features,
        );
        await repo.updatePlan(updatedPlan);
      }

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(widget.plan == null ? 'Plan added' : 'Plan updated'),
          ),
        );
        Navigator.pop(context);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text('Error saving plan: $e')));
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(
          widget.plan == null
              ? 'Add Subscription Plan'
              : 'Edit Subscription Plan',
        ),
      ),
      body: _isLoading
          ? const Center(child: CircularProgressIndicator())
          : SingleChildScrollView(
              padding: const EdgeInsets.all(16),
              child: Form(
                key: _formKey,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    TextFormField(
                      controller: _nameController,
                      decoration: const InputDecoration(
                        labelText: 'Plan Name',
                        border: OutlineInputBorder(),
                      ),
                      validator: (value) => value == null || value.isEmpty
                          ? 'Please enter a name'
                          : null,
                    ),
                    const SizedBox(height: 16),
                    TextFormField(
                      controller: _priceController,
                      decoration: const InputDecoration(
                        labelText: 'Price',
                        prefixText: '\$ ',
                        border: OutlineInputBorder(),
                      ),
                      keyboardType: const TextInputType.numberWithOptions(
                        decimal: true,
                      ),
                      validator: (value) {
                        if (value == null || value.isEmpty)
                          return 'Please enter a price';
                        if (double.tryParse(value) == null)
                          return 'Invalid price';
                        return null;
                      },
                    ),
                    const SizedBox(height: 16),
                    TextFormField(
                      controller: _durationController,
                      decoration: const InputDecoration(
                        labelText: 'Duration (e.g. Monthly, Yearly)',
                        border: OutlineInputBorder(),
                      ),
                      validator: (value) => value == null || value.isEmpty
                          ? 'Please enter a duration'
                          : null,
                    ),
                    const SizedBox(height: 16),
                    TextFormField(
                      controller: _descriptionController,
                      decoration: const InputDecoration(
                        labelText: 'Description',
                        border: OutlineInputBorder(),
                      ),
                      maxLines: 2,
                      validator: (value) => value == null || value.isEmpty
                          ? 'Please enter a description'
                          : null,
                    ),
                    const SizedBox(height: 24),
                    Text(
                      'Features',
                      style: Theme.of(context).textTheme.titleMedium,
                    ),
                    const SizedBox(height: 8),
                    ..._featureControllers.asMap().entries.map((entry) {
                      final index = entry.key;
                      final controller = entry.value;
                      return Padding(
                        padding: const EdgeInsets.only(bottom: 8.0),
                        child: Row(
                          children: [
                            Expanded(
                              child: TextFormField(
                                controller: controller,
                                decoration: InputDecoration(
                                  labelText: 'Feature ${index + 1}',
                                  border: const OutlineInputBorder(),
                                  isDense: true,
                                ),
                                validator: (val) =>
                                    val != null && val.isEmpty && index == 0
                                    ? 'At least one feature required'
                                    : null,
                              ),
                            ),
                            const SizedBox(width: 8),
                            if (_featureControllers.length > 1)
                              IconButton(
                                icon: const Icon(
                                  Icons.remove_circle_outline,
                                  color: Colors.red,
                                ),
                                onPressed: () => _removeFeature(index),
                              ),
                          ],
                        ),
                      );
                    }).toList(),
                    OutlinedButton.icon(
                      onPressed: _addFeature,
                      icon: const Icon(Icons.add),
                      label: const Text('Add Feature'),
                    ),
                    const SizedBox(height: 32),
                    ElevatedButton(
                      onPressed: _savePlan,
                      style: ElevatedButton.styleFrom(
                        padding: const EdgeInsets.symmetric(vertical: 16),
                        backgroundColor: const Color(0xFF1E2A47),
                        foregroundColor: Colors.white,
                      ),
                      child: Text(
                        widget.plan == null ? 'Create Plan' : 'Update Plan',
                        style: const TextStyle(
                          fontSize: 16,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ),
    );
  }
}
